
const Colors = {
    white: '#ffffff',
    lightGrey: '#d3d3d3',
    grey: '#f7f7f7',
    greyHeaderText: '#c0c0c0',
    lightTextColorGrey: '#3E4A59',
    textGreyColor: '#555555',
    backgroundGrey: '#F2F2F2',
    dividerGrey: '#EEEEEE',
    lighterGrey: '#e6e6e6',
    black: '#333333',
    suvaGrey: '#888888',
    green: '#63C156',
    whiteSmoke: '#F7F7F7',
    persianRed: '#D12F2F',
    ashColor: '#CCCCCC',
    lightYellow: '#FFF7D7',
    blue: '#017aff',
    darkRed: '#b52424',
    eclipse: '#3a3a3a',
    lightBlue: '#198ebc',
    lightRedShade: '#F64F4B',
    lightGrayShade: '#F2F2F2',
    lightBrown: '#F49A38',
    lightYellowShade: '#FFE36E',
    limeColor: '#B0D657',
    ashGrey: '#efeff5',
    lightGold: '#F5A623',
    greyShadow: '#999999',
    crayola: '#323643',
    lightRed: '#ffefef',
    gallery: '#EEEEEE',
    silver: '#BBBBBB',
    aliceBlue: '#FAFBFD',
    outrageousOrange: '#FE561F',
    suluGreen: '#D1EA8C',
    alizarinRed: '#D82927',
    warning: '#F0AD4E',
    carrotOrange: '#F47925',
    mediumGray: '#ADADAD',
    gunmetal: '#242A37',
    shadowGrey: '#000000',
    icon_purple: '#9D7BD2',
    icon_green: '#A3C05F',
    textBlue: '#198EBC',
    ratingYellow: '#F7D823',
    ratingGreen: '#387C2E',
    mongoose: '#AF9E80',
    tacha: '#D4C76D',
    lightBlack: '#31394D',
    primaryColor: '#57B864',
    dark_grey: '#212121',
    statusBarColor: '#0E1C24',
    red: '#FF0000',
    tabGrey: '#AAAAAA',
    lightWhite: '#EDEDF3',
    springGreen: '#32FF83',
    transparent: 'transparent',
    underlineColor: '#CACACA',
    yellow: '#FFFF00',
    gondola: '#363636',
    malachite: '#14CB53',
    middleGrey: '#777777',
    veryLightWhite: '#F5F5F5',
    WhiteSmoke: '#EAEAEA',
    darkBlack: '#000',
    viking: '#42ADBB',
    PaleOyster: '#9E8D6E',
    PurpleHeart: '#5827B7',
    neroGrey: '#252525',
    DarkOrange: '#E67D3B',
    BittersweetRed: '#FF665A',
    paleBlue: '#65bcd8',
    chipBlack: '#151515',
    chipBg: '#EFEFEF',
    bigFoodieOrange: '#ED7656',
    ToolBarPrimaryColor: '#ffffff', //toolbar color.
    primaryTextColor: '#333333', // primary text color(kinda black color) across the App,
    secondaryTextColor: '#888888', // secondary text color (grey color) for the app, like labels.
    notificationCountBgColor: '#E67D3B', // background color for notification count on toolbar.
    sideMenuBackgroundColor: '#EAEAEA', // background color of the navigation drawer.
    sideMenuHeaderBackgroundColor: '#ffffff', // background color of the navigation drawer's header.
    accentColor: '#63C156', // primary text color(kinda black color) across the App,
    linkBlue: "#1DA4FC",
    violet: '#794BC4'
};

export default Colors;
